# Site settings
title: Specialist WiFi Network Design & Management
email: hello@polkaspots.com
description: > # this means to ignore newlines until "baseurl:"
  Specialist WiFi network design and installation. Anywhere, anyhow.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.polkaspots.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
# markdown: kramdown

markdown: redcarpet
# pygments: true
# baseurl: /
